package system.dao;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("system_cache", "id", Cache.class);
		arp.addMapping("system_file", "fid", File.class);
		arp.addMapping("system_menu_link", "id", MenuLink.class);
		arp.addMapping("system_message", "id", Message.class);
		arp.addMapping("system_permission", "id", Permission.class);
		arp.addMapping("system_role", "rid", Role.class);
		arp.addMapping("system_role_group", "id", RoleGroup.class);
		// Composite Primary Key order: mlid,rid
		arp.addMapping("system_role_menu_link", "mlid,rid", RoleMenuLink.class);
		// Composite Primary Key order: pid,rid
		arp.addMapping("system_role_permission", "pid,rid", RolePermission.class);
		arp.addMapping("system_session", "id", Session.class);
		arp.addMapping("system_sms_api", "id", SmsApi.class);
		arp.addMapping("system_sms_log", "id", SmsLog.class);
		arp.addMapping("system_sms_template", "id", SmsTemplate.class);
		arp.addMapping("system_task", "id", Task.class);
		arp.addMapping("system_todo", "id", Todo.class);
		arp.addMapping("system_user", "uid", User.class);
		// Composite Primary Key order: rid,uid
		arp.addMapping("system_user_role", "rid,uid", UserRole.class);
		arp.addMapping("system_variable", "name", Variable.class);
		arp.addMapping("system_vocabulary", "vid", Vocabulary.class);
		arp.addMapping("system_vocabulary_term", "tid", VocabularyTerm.class);
	}
}

