package system.dao;

import system.dao.base.BaseCache;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cache extends BaseCache<Cache> {
	public static final Cache dao = new Cache();
}
