package system.dao;

import system.dao.base.BaseFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	public static final File dao = new File();
}
