package system.dao;

import system.dao.base.BaseMenuLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuLink extends BaseMenuLink<MenuLink> {
	public static final MenuLink dao = new MenuLink();
}
