package system.dao;

import system.dao.base.BaseRoleMenuLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenuLink extends BaseRoleMenuLink<RoleMenuLink> {
	public static final RoleMenuLink dao = new RoleMenuLink();
}
