package system.dao;

import system.dao.base.BaseRoleGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleGroup extends BaseRoleGroup<RoleGroup> {
	public static final RoleGroup dao = new RoleGroup();
}
