package system.dao;

import system.dao.base.BaseSmsApi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsApi extends BaseSmsApi<SmsApi> {
	public static final SmsApi dao = new SmsApi();
}
