package system.dao;

import system.dao.base.BaseSmsLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsLog extends BaseSmsLog<SmsLog> {
	public static final SmsLog dao = new SmsLog();
}
