package system.dao;

import system.dao.base.BaseSmsTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsTemplate extends BaseSmsTemplate<SmsTemplate> {
	public static final SmsTemplate dao = new SmsTemplate();
}
