package system.dao;

import system.dao.base.BaseTodo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Todo extends BaseTodo<Todo> {
	public static final Todo dao = new Todo();
}
