package system.dao;

import system.dao.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole();
}
