package system.dao;

import system.dao.base.BaseVariable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Variable extends BaseVariable<Variable> {
	public static final Variable dao = new Variable();
}
