package system.dao;

import system.dao.base.BaseVocabularyTerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VocabularyTerm extends BaseVocabularyTerm<VocabularyTerm> {
	public static final VocabularyTerm dao = new VocabularyTerm();
}
