package system.dao;

import system.dao.base.BaseVocabulary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vocabulary extends BaseVocabulary<Vocabulary> {
	public static final Vocabulary dao = new Vocabulary();
}
