package app.dao;

import app.dao.base.BaseBTAddrProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BTAddrProvince extends BaseBTAddrProvince<BTAddrProvince> {
	public static final BTAddrProvince dao = new BTAddrProvince();
}
