package app.dao;

import app.dao.base.BaseBTAddrCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BTAddrCity extends BaseBTAddrCity<BTAddrCity> {
	public static final BTAddrCity dao = new BTAddrCity();
}
