package app.dao;

import app.dao.base.BaseBTAddrDistrict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BTAddrDistrict extends BaseBTAddrDistrict<BTAddrDistrict> {
	public static final BTAddrDistrict dao = new BTAddrDistrict();
}
