package app.dao;

import app.dao.base.BaseBTScale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BTScale extends BaseBTScale<BTScale> {
	public static final BTScale dao = new BTScale();
}
