package app.dao;

import app.dao.base.BaseBudgetClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetClass extends BaseBudgetClass<BudgetClass> {
	public static final BudgetClass dao = new BudgetClass();
}
