package app.dao;

import app.dao.base.BaseBudgetItemCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetItemCost extends BaseBudgetItemCost<BudgetItemCost> {
	public static final BudgetItemCost dao = new BudgetItemCost();
}
