package app.dao;

import app.dao.base.BaseBudget;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Budget extends BaseBudget<Budget> {
	public static final Budget dao = new Budget();
}
