package app.dao;

import app.dao.base.BaseBudgetPackage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetPackage extends BaseBudgetPackage<BudgetPackage> {
	public static final BudgetPackage dao = new BudgetPackage();
}
