package app.dao;

import app.dao.base.BaseBudgetLineItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetLineItem extends BaseBudgetLineItem<BudgetLineItem> {
	public static final BudgetLineItem dao = new BudgetLineItem();
}
