package app.dao;

import app.dao.base.BaseBudgetPackageItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetPackageItem extends BaseBudgetPackageItem<BudgetPackageItem> {
	public static final BudgetPackageItem dao = new BudgetPackageItem();
}
