package app.dao;

import app.dao.base.BaseBudgetItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetItem extends BaseBudgetItem<BudgetItem> {
	public static final BudgetItem dao = new BudgetItem();
}
