package app.dao;

import app.dao.base.BaseBudgetItemAmount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetItemAmount extends BaseBudgetItemAmount<BudgetItemAmount> {
	public static final BudgetItemAmount dao = new BudgetItemAmount();
}
