package app.dao;

import app.dao.base.BaseBudgetPackageVariationItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BudgetPackageVariationItem extends BaseBudgetPackageVariationItem<BudgetPackageVariationItem> {
	public static final BudgetPackageVariationItem dao = new BudgetPackageVariationItem();
}
