package app.dao;

import app.dao.base.BaseCompanyInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyInfo extends BaseCompanyInfo<CompanyInfo> {
	public static final CompanyInfo dao = new CompanyInfo();
}
