package app.dao;

import app.dao.base.BaseContactForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContactForm extends BaseContactForm<ContactForm> {
	public static final ContactForm dao = new ContactForm();
}
