package app.dao;

import app.dao.base.BaseContactInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContactInfo extends BaseContactInfo<ContactInfo> {
	public static final ContactInfo dao = new ContactInfo();
}
