package app.dao;

import app.dao.base.BaseCrmDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmDepartment extends BaseCrmDepartment<CrmDepartment> {
	public static final CrmDepartment dao = new CrmDepartment();
}
