package app.dao;

import app.dao.base.BaseCrmJobTitle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmJobTitle extends BaseCrmJobTitle<CrmJobTitle> {
	public static final CrmJobTitle dao = new CrmJobTitle();
}
