package app.dao;

import app.dao.base.BaseCrmStaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmStaff extends BaseCrmStaff<CrmStaff> {
	public static final CrmStaff dao = new CrmStaff();
}
