package app.dao;

import app.dao.base.BaseCrmStaffExtra;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmStaffExtra extends BaseCrmStaffExtra<CrmStaffExtra> {
	public static final CrmStaffExtra dao = new CrmStaffExtra();
}
