package app.dao;

import app.dao.base.BaseMarketingRecordFollow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MarketingRecordFollow extends BaseMarketingRecordFollow<MarketingRecordFollow> {
	public static final MarketingRecordFollow dao = new MarketingRecordFollow();
}
