package app.dao;

import app.dao.base.BaseMarketingRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MarketingRecord extends BaseMarketingRecord<MarketingRecord> {
	public static final MarketingRecord dao = new MarketingRecord();
}
