package app.dao;

import app.dao.base.BaseMarketingSaleSourceType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MarketingSaleSourceType extends BaseMarketingSaleSourceType<MarketingSaleSourceType> {
	public static final MarketingSaleSourceType dao = new MarketingSaleSourceType();
}
