package app.dao;

import app.dao.base.BaseMarketingSaleSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MarketingSaleSource extends BaseMarketingSaleSource<MarketingSaleSource> {
	public static final MarketingSaleSource dao = new MarketingSaleSource();
}
