package system.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public void setFid(java.lang.Integer fid) {
		set("fid", fid);
	}

	public java.lang.Integer getFid() {
		return get("fid");
	}

	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}

	public java.lang.String getFileName() {
		return get("file_name");
	}

	public void setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
	}

	public java.lang.String getFilePath() {
		return get("file_path");
	}

	public void setFileMime(java.lang.String fileMime) {
		set("file_mime", fileMime);
	}

	public java.lang.String getFileMime() {
		return get("file_mime");
	}

	public void setFileSrcName(java.lang.String fileSrcName) {
		set("file_src_name", fileSrcName);
	}

	public java.lang.String getFileSrcName() {
		return get("file_src_name");
	}

	public void setFileSize(java.lang.Integer fileSize) {
		set("file_size", fileSize);
	}

	public java.lang.Integer getFileSize() {
		return get("file_size");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}

	public java.lang.Integer getUid() {
		return get("uid");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}

	public java.lang.Integer getCreated() {
		return get("created");
	}

}
