package system.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenuLink<M extends BaseMenuLink<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPlid(java.lang.Integer plid) {
		set("plid", plid);
	}

	public java.lang.Integer getPlid() {
		return get("plid");
	}

	public void setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
	}

	public java.lang.Integer getMenuId() {
		return get("menu_id");
	}

	public void setLinkPath(java.lang.String linkPath) {
		set("link_path", linkPath);
	}

	public java.lang.String getLinkPath() {
		return get("link_path");
	}

	public void setLinkTitle(java.lang.String linkTitle) {
		set("link_title", linkTitle);
	}

	public java.lang.String getLinkTitle() {
		return get("link_title");
	}

	public void setHidden(java.lang.Integer hidden) {
		set("hidden", hidden);
	}

	public java.lang.Integer getHidden() {
		return get("hidden");
	}

	public void setExternal(java.lang.Integer external) {
		set("external", external);
	}

	public java.lang.Integer getExternal() {
		return get("external");
	}

	public void setHasChildren(java.lang.Integer hasChildren) {
		set("has_children", hasChildren);
	}

	public java.lang.Integer getHasChildren() {
		return get("has_children");
	}

	public void setExpanded(java.lang.Integer expanded) {
		set("expanded", expanded);
	}

	public java.lang.Integer getExpanded() {
		return get("expanded");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setDepth(java.lang.Integer depth) {
		set("depth", depth);
	}

	public java.lang.Integer getDepth() {
		return get("depth");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}

	public java.lang.String getTarget() {
		return get("target");
	}

}
