package system.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCron(java.lang.String cron) {
		set("cron", cron);
	}

	public java.lang.String getCron() {
		return get("cron");
	}

	public void setTaskname(java.lang.String taskname) {
		set("taskname", taskname);
	}

	public java.lang.String getTaskname() {
		return get("taskname");
	}

	public void setDaemon(java.lang.Integer daemon) {
		set("daemon", daemon);
	}

	public java.lang.Integer getDaemon() {
		return get("daemon");
	}

	public void setEnable(java.lang.Integer enable) {
		set("enable", enable);
	}

	public java.lang.Integer getEnable() {
		return get("enable");
	}

}
