package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmStaffExtra<M extends BaseCrmStaffExtra<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGraduatedSchool(java.lang.String graduatedSchool) {
		set("graduated_school", graduatedSchool);
	}

	public java.lang.String getGraduatedSchool() {
		return get("graduated_school");
	}

	public void setMajor(java.lang.String major) {
		set("major", major);
	}

	public java.lang.String getMajor() {
		return get("major");
	}

	public void setEducation(java.lang.String education) {
		set("education", education);
	}

	public java.lang.String getEducation() {
		return get("education");
	}

	public void setDegree(java.lang.String degree) {
		set("degree", degree);
	}

	public java.lang.String getDegree() {
		return get("degree");
	}

	public void setHometown(java.lang.String hometown) {
		set("hometown", hometown);
	}

	public java.lang.String getHometown() {
		return get("hometown");
	}

	public void setHometownAddr(java.lang.String hometownAddr) {
		set("hometown_addr", hometownAddr);
	}

	public java.lang.String getHometownAddr() {
		return get("hometown_addr");
	}

	public void setHometownType(java.lang.String hometownType) {
		set("hometown_type", hometownType);
	}

	public java.lang.String getHometownType() {
		return get("hometown_type");
	}

	public void setIdNo(java.lang.String idNo) {
		set("id_no", idNo);
	}

	public java.lang.String getIdNo() {
		return get("id_no");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setLandscape(java.lang.String landscape) {
		set("landscape", landscape);
	}

	public java.lang.String getLandscape() {
		return get("landscape");
	}

	public void setMaritalStatus(java.lang.Integer maritalStatus) {
		set("marital_status", maritalStatus);
	}

	public java.lang.Integer getMaritalStatus() {
		return get("marital_status");
	}

	public void setHealth(java.lang.String health) {
		set("health", health);
	}

	public java.lang.String getHealth() {
		return get("health");
	}

	public void setBankCardName(java.lang.String bankCardName) {
		set("bank_card_name", bankCardName);
	}

	public java.lang.String getBankCardName() {
		return get("bank_card_name");
	}

	public void setBankCardNo(java.lang.String bankCardNo) {
		set("bank_card_no", bankCardNo);
	}

	public java.lang.String getBankCardNo() {
		return get("bank_card_no");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return get("contact");
	}

	public void setContactRelation(java.lang.String contactRelation) {
		set("contact_relation", contactRelation);
	}

	public java.lang.String getContactRelation() {
		return get("contact_relation");
	}

	public void setContactRelationPhone(java.lang.String contactRelationPhone) {
		set("contact_relation_phone", contactRelationPhone);
	}

	public java.lang.String getContactRelationPhone() {
		return get("contact_relation_phone");
	}

	public void setAwards(java.lang.String awards) {
		set("awards", awards);
	}

	public java.lang.String getAwards() {
		return get("awards");
	}

	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}

	public java.lang.String getCertificate() {
		return get("certificate");
	}

	public void setWelfare(java.lang.String welfare) {
		set("welfare", welfare);
	}

	public java.lang.String getWelfare() {
		return get("welfare");
	}

	public void setSocialSecurity(java.lang.String socialSecurity) {
		set("social_security", socialSecurity);
	}

	public java.lang.String getSocialSecurity() {
		return get("social_security");
	}

	public void setRegularTime(java.lang.String regularTime) {
		set("regular_time", regularTime);
	}

	public java.lang.String getRegularTime() {
		return get("regular_time");
	}

	public void setLeaveTime(java.lang.String leaveTime) {
		set("leave_time", leaveTime);
	}

	public java.lang.String getLeaveTime() {
		return get("leave_time");
	}

}
