package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBudgetLineItem<M extends BaseBudgetLineItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSection(java.lang.Integer section) {
		set("section", section);
	}

	public java.lang.Integer getSection() {
		return get("section");
	}

	public void setBudgetId(java.lang.Integer budgetId) {
		set("budget_id", budgetId);
	}

	public java.lang.Integer getBudgetId() {
		return get("budget_id");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setLineItemField(java.lang.String lineItemField) {
		set("line_item_field", lineItemField);
	}

	public java.lang.String getLineItemField() {
		return get("line_item_field");
	}

	public void setLineItemName(java.lang.String lineItemName) {
		set("line_item_name", lineItemName);
	}

	public java.lang.String getLineItemName() {
		return get("line_item_name");
	}

	public void setLineItemComment(java.lang.String lineItemComment) {
		set("line_item_comment", lineItemComment);
	}

	public java.lang.String getLineItemComment() {
		return get("line_item_comment");
	}

	public void setLineItemAmount(java.math.BigDecimal lineItemAmount) {
		set("line_item_amount", lineItemAmount);
	}

	public java.math.BigDecimal getLineItemAmount() {
		return get("line_item_amount");
	}

}
