package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBudgetClass<M extends BaseBudgetClass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBudgetId(java.lang.Integer budgetId) {
		set("budget_id", budgetId);
	}

	public java.lang.Integer getBudgetId() {
		return get("budget_id");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

	public void setProjectItemCatalogId(java.lang.Integer projectItemCatalogId) {
		set("project_item_catalog_id", projectItemCatalogId);
	}

	public java.lang.Integer getProjectItemCatalogId() {
		return get("project_item_catalog_id");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("room_id", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("room_id");
	}

	public void setSection(java.lang.Integer section) {
		set("section", section);
	}

	public java.lang.Integer getSection() {
		return get("section");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setNo(java.lang.Integer no) {
		set("no", no);
	}

	public java.lang.Integer getNo() {
		return get("no");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setHasChildren(java.lang.Integer hasChildren) {
		set("has_children", hasChildren);
	}

	public java.lang.Integer getHasChildren() {
		return get("has_children");
	}

	public void setSubtotal(java.math.BigDecimal subtotal) {
		set("subtotal", subtotal);
	}

	public java.math.BigDecimal getSubtotal() {
		return get("subtotal");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}

	public java.lang.Integer getCreated() {
		return get("created");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

	public void setUpdated(java.lang.Integer updated) {
		set("updated", updated);
	}

	public java.lang.Integer getUpdated() {
		return get("updated");
	}

}
