package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBudgetItem<M extends BaseBudgetItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBudgetId(java.lang.Integer budgetId) {
		set("budget_id", budgetId);
	}

	public java.lang.Integer getBudgetId() {
		return get("budget_id");
	}

	public void setBudgetClassId(java.lang.Integer budgetClassId) {
		set("budget_class_id", budgetClassId);
	}

	public java.lang.Integer getBudgetClassId() {
		return get("budget_class_id");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("room_id", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("room_id");
	}

	public void setSection(java.lang.Integer section) {
		set("section", section);
	}

	public java.lang.Integer getSection() {
		return get("section");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setNo(java.lang.Integer no) {
		set("no", no);
	}

	public java.lang.Integer getNo() {
		return get("no");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setProjectItemId(java.lang.Integer projectItemId) {
		set("project_item_id", projectItemId);
	}

	public java.lang.Integer getProjectItemId() {
		return get("project_item_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}

	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setMaterialAttached(java.lang.Integer materialAttached) {
		set("material_attached", materialAttached);
	}

	public java.lang.Integer getMaterialAttached() {
		return get("material_attached");
	}

	public void setMaterialId(java.lang.Integer materialId) {
		set("material_id", materialId);
	}

	public java.lang.Integer getMaterialId() {
		return get("material_id");
	}

	public void setMaterialInfo(java.lang.String materialInfo) {
		set("material_info", materialInfo);
	}

	public java.lang.String getMaterialInfo() {
		return get("material_info");
	}

	public void setPrintable(java.lang.Integer printable) {
		set("printable", printable);
	}

	public java.lang.Integer getPrintable() {
		return get("printable");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}

	public java.lang.Integer getCreated() {
		return get("created");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateUid(java.lang.Integer createUid) {
		set("create_uid", createUid);
	}

	public java.lang.Integer getCreateUid() {
		return get("create_uid");
	}

	public void setUpdated(java.lang.Integer updated) {
		set("updated", updated);
	}

	public java.lang.Integer getUpdated() {
		return get("updated");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUid(java.lang.Integer updateUid) {
		set("update_uid", updateUid);
	}

	public java.lang.Integer getUpdateUid() {
		return get("update_uid");
	}

}
