package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContactInfo<M extends BaseContactInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
	}

	public java.lang.Integer getCompanyId() {
		return get("company_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setTelReserve(java.lang.String telReserve) {
		set("tel_reserve", telReserve);
	}

	public java.lang.String getTelReserve() {
		return get("tel_reserve");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setQQ(java.lang.String QQ) {
		set("QQ", QQ);
	}

	public java.lang.String getQQ() {
		return get("QQ");
	}

	public void setWeixin(java.lang.String weixin) {
		set("weixin", weixin);
	}

	public java.lang.String getWeixin() {
		return get("weixin");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}

	public java.lang.Integer getCreated() {
		return get("created");
	}

	public void setCreateUid(java.lang.Integer createUid) {
		set("create_uid", createUid);
	}

	public java.lang.Integer getCreateUid() {
		return get("create_uid");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}

	public java.lang.String getCreateName() {
		return get("create_name");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setUpdated(java.lang.Integer updated) {
		set("updated", updated);
	}

	public java.lang.Integer getUpdated() {
		return get("updated");
	}

	public void setUpdateUid(java.lang.Integer updateUid) {
		set("update_uid", updateUid);
	}

	public java.lang.Integer getUpdateUid() {
		return get("update_uid");
	}

	public void setUpdateName(java.lang.String updateName) {
		set("update_name", updateName);
	}

	public java.lang.String getUpdateName() {
		return get("update_name");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

}
