package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyInfo<M extends BaseCompanyInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAlias(java.lang.String alias) {
		set("alias", alias);
	}

	public java.lang.String getAlias() {
		return get("alias");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
	}

	public java.lang.String getProvinceName() {
		return get("province_name");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}

	public java.lang.String getCityName() {
		return get("city_name");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("district_id", districtId);
	}

	public java.lang.Integer getDistrictId() {
		return get("district_id");
	}

	public void setDistrictName(java.lang.String districtName) {
		set("district_name", districtName);
	}

	public java.lang.String getDistrictName() {
		return get("district_name");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setScaleId(java.lang.Integer scaleId) {
		set("scale_id", scaleId);
	}

	public java.lang.Integer getScaleId() {
		return get("scale_id");
	}

	public void setScaleSize(java.lang.String scaleSize) {
		set("scale_size", scaleSize);
	}

	public java.lang.String getScaleSize() {
		return get("scale_size");
	}

	public void setEstablishedTime(java.lang.String establishedTime) {
		set("established_time", establishedTime);
	}

	public java.lang.String getEstablishedTime() {
		return get("established_time");
	}

	public void setLegalRepresentative(java.lang.String legalRepresentative) {
		set("legal_representative", legalRepresentative);
	}

	public java.lang.String getLegalRepresentative() {
		return get("legal_representative");
	}

	public void setPrincipal(java.lang.String principal) {
		set("principal", principal);
	}

	public java.lang.String getPrincipal() {
		return get("principal");
	}

	public void setPrincipalTel(java.lang.String principalTel) {
		set("principal_tel", principalTel);
	}

	public java.lang.String getPrincipalTel() {
		return get("principal_tel");
	}

	public void setPrincipalWeixin(java.lang.String principalWeixin) {
		set("principal_weixin", principalWeixin);
	}

	public java.lang.String getPrincipalWeixin() {
		return get("principal_weixin");
	}

	public void setReceptionTel(java.lang.String receptionTel) {
		set("reception_tel", receptionTel);
	}

	public java.lang.String getReceptionTel() {
		return get("reception_tel");
	}

	public void setBranchCompany(java.lang.String branchCompany) {
		set("branch_company", branchCompany);
	}

	public java.lang.String getBranchCompany() {
		return get("branch_company");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}

	public java.lang.Integer getCreated() {
		return get("created");
	}

	public void setCreateUid(java.lang.Integer createUid) {
		set("create_uid", createUid);
	}

	public java.lang.Integer getCreateUid() {
		return get("create_uid");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}

	public java.lang.String getCreateName() {
		return get("create_name");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setUpdated(java.lang.Integer updated) {
		set("updated", updated);
	}

	public java.lang.Integer getUpdated() {
		return get("updated");
	}

	public void setUpdateUid(java.lang.Integer updateUid) {
		set("update_uid", updateUid);
	}

	public java.lang.Integer getUpdateUid() {
		return get("update_uid");
	}

	public void setUpdateName(java.lang.String updateName) {
		set("update_name", updateName);
	}

	public java.lang.String getUpdateName() {
		return get("update_name");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

}
