package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMarketingRecordFollow<M extends BaseMarketingRecordFollow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRecordId(java.lang.Integer recordId) {
		set("record_id", recordId);
	}

	public java.lang.Integer getRecordId() {
		return get("record_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}

	public java.lang.Integer getCreated() {
		return get("created");
	}

	public void setCreateUid(java.lang.Integer createUid) {
		set("create_uid", createUid);
	}

	public java.lang.Integer getCreateUid() {
		return get("create_uid");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}

	public java.lang.String getCreateName() {
		return get("create_name");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

}
