package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBudgetItemCost<M extends BaseBudgetItemCost<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBudgetId(java.lang.Integer budgetId) {
		set("budget_id", budgetId);
	}

	public java.lang.Integer getBudgetId() {
		return get("budget_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}

	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public void setCostNum(java.math.BigDecimal costNum) {
		set("cost_num", costNum);
	}

	public java.math.BigDecimal getCostNum() {
		return get("cost_num");
	}

	public void setCostLabor(java.math.BigDecimal costLabor) {
		set("cost_labor", costLabor);
	}

	public java.math.BigDecimal getCostLabor() {
		return get("cost_labor");
	}

	public void setCostLaborFeeId(java.lang.Integer costLaborFeeId) {
		set("cost_labor_fee_id", costLaborFeeId);
	}

	public java.lang.Integer getCostLaborFeeId() {
		return get("cost_labor_fee_id");
	}

	public void setCostAssist(java.math.BigDecimal costAssist) {
		set("cost_assist", costAssist);
	}

	public java.math.BigDecimal getCostAssist() {
		return get("cost_assist");
	}

	public void setCostAssistFeeId(java.lang.Integer costAssistFeeId) {
		set("cost_assist_fee_id", costAssistFeeId);
	}

	public java.lang.Integer getCostAssistFeeId() {
		return get("cost_assist_fee_id");
	}

	public void setCostMaterial(java.math.BigDecimal costMaterial) {
		set("cost_material", costMaterial);
	}

	public java.math.BigDecimal getCostMaterial() {
		return get("cost_material");
	}

	public void setPriceCostLabor(java.math.BigDecimal priceCostLabor) {
		set("price_cost_labor", priceCostLabor);
	}

	public java.math.BigDecimal getPriceCostLabor() {
		return get("price_cost_labor");
	}

	public void setPriceCostAssist(java.math.BigDecimal priceCostAssist) {
		set("price_cost_assist", priceCostAssist);
	}

	public java.math.BigDecimal getPriceCostAssist() {
		return get("price_cost_assist");
	}

	public void setPriceCostMaterial(java.math.BigDecimal priceCostMaterial) {
		set("price_cost_material", priceCostMaterial);
	}

	public java.math.BigDecimal getPriceCostMaterial() {
		return get("price_cost_material");
	}

	public void setUpdated(java.lang.Integer updated) {
		set("updated", updated);
	}

	public java.lang.Integer getUpdated() {
		return get("updated");
	}

}
