package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmJobTitle<M extends BaseCrmJobTitle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDepartment(java.lang.Integer department) {
		set("department", department);
	}

	public java.lang.Integer getDepartment() {
		return get("department");
	}

	public void setRole(java.lang.String role) {
		set("role", role);
	}

	public java.lang.String getRole() {
		return get("role");
	}

	public void setQueryToken(java.lang.String queryToken) {
		set("query_token", queryToken);
	}

	public java.lang.String getQueryToken() {
		return get("query_token");
	}

}
