package app.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMarketingRecord<M extends BaseMarketingRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
	}

	public java.lang.Integer getCompanyId() {
		return get("company_id");
	}

	public void setSalesmanDepartmentId(java.lang.Integer salesmanDepartmentId) {
		set("salesman_department_id", salesmanDepartmentId);
	}

	public java.lang.Integer getSalesmanDepartmentId() {
		return get("salesman_department_id");
	}

	public void setSalesmanDepartmentName(java.lang.String salesmanDepartmentName) {
		set("salesman_department_name", salesmanDepartmentName);
	}

	public java.lang.String getSalesmanDepartmentName() {
		return get("salesman_department_name");
	}

	public void setSalesmanId(java.lang.Integer salesmanId) {
		set("salesman_id", salesmanId);
	}

	public java.lang.Integer getSalesmanId() {
		return get("salesman_id");
	}

	public void setSalesmanName(java.lang.String salesmanName) {
		set("salesman_name", salesmanName);
	}

	public java.lang.String getSalesmanName() {
		return get("salesman_name");
	}

	public void setSourceTypeId(java.lang.Integer sourceTypeId) {
		set("source_type_id", sourceTypeId);
	}

	public java.lang.Integer getSourceTypeId() {
		return get("source_type_id");
	}

	public void setSourceTypeName(java.lang.String sourceTypeName) {
		set("source_type_name", sourceTypeName);
	}

	public java.lang.String getSourceTypeName() {
		return get("source_type_name");
	}

	public void setSourceId(java.lang.Integer sourceId) {
		set("source_id", sourceId);
	}

	public java.lang.Integer getSourceId() {
		return get("source_id");
	}

	public void setSourceName(java.lang.String sourceName) {
		set("source_name", sourceName);
	}

	public java.lang.String getSourceName() {
		return get("source_name");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
	}

	public java.lang.Integer getDeleted() {
		return get("deleted");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}

	public java.lang.Integer getCreated() {
		return get("created");
	}

	public void setCreateUid(java.lang.Integer createUid) {
		set("create_uid", createUid);
	}

	public java.lang.Integer getCreateUid() {
		return get("create_uid");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}

	public java.lang.String getCreateName() {
		return get("create_name");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setUpdated(java.lang.Integer updated) {
		set("updated", updated);
	}

	public java.lang.Integer getUpdated() {
		return get("updated");
	}

	public void setUpdateUid(java.lang.Integer updateUid) {
		set("update_uid", updateUid);
	}

	public java.lang.Integer getUpdateUid() {
		return get("update_uid");
	}

	public void setUpdateName(java.lang.String updateName) {
		set("update_name", updateName);
	}

	public java.lang.String getUpdateName() {
		return get("update_name");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

}
